### ISSUE TITLE
pysolr dependency missing from requirements.txt

### ISSUE THREAD

**Issue by kshepherd** [the-library-code/dspace-rest-python#7]

**Comment by abubelinha** [comment]
I was to open an issue but I guess this is the same:

1. Installed with `pip install dspace_rest_client`
2. Tried to run [example.py](https://github.com/the-library-code/dspace-rest-python/blob/main/example.py) with my login information using https://demo.dspace.org/server/api for `DSPACE_API_ENDPOINT`.
3. Got this error:

```Python
Traceback (most recent call last):
  File "test_dspace.py", line 65, in <module>
    dspace_rest_python_example()
  File "test_dspace.py", line 32, in dspace_rest_python_example
    from dspace_rest_client.client import DSpaceClient
  File "C:\Python38\lib\site-packages\dspace_rest_client\client.py", line 24, in <module>
    import pysolr
ModuleNotFoundError: No module named 'pysolr'
```

I take the opportunity to ask a couple of questions:
- Is the above url correct as a `DSPACE_API_ENDPOINT` for testing? 
  It returns a JSON interface, while other demo url interfaces I see look quite different: https://demo6.dspace.org/rest
- I am new to DSpace and have never used it (not even human UI).  I need to upload hundreds of items to my institution server (still waiting for login credentials) but when trying my.server.url/rest/status it returns this version. 
```XML
<status>
<apiVersion>6</apiVersion>
<authenticated>false</authenticated>
<okay>true</okay>
<sourceVersion>6.3_1.1.1</sourceVersion>
</status>
```
Do I have any chances to interact with it using this Python package?
If not, do you know of other alternatives for bulk document uploads to that DSpace version api?

Thanks a lot for your help
@abubelinha

**Comment by kshepherd** [comment]
Resolved at version 0.1.9
PyPI (https://pypi.org/project/dspace-rest-client/0.1.9/)
Git tag here: https://github.com/the-library-code/dspace-rest-python/tree/dspace-rest-client-0.1.9
